export const Icon = {
  homeIcon: require('../assets/images/home.png'),
  moreIcon: require('../assets/images/star.png'),
  traceIcon: require('../assets/images/traceIcon.png'),
  plannerIcon: require('../assets/images/calendar.png'),
  menu: require('../assets/images/menu.png'),
  bell: require('../assets/images/bell.png'),
  search: require('../assets/images/search.png'),
  fuelFull: require('../assets/images/fuelFull.png'),
  fuelFullPipe: require('../assets/images/fuelFullPipe.png'),
  fuelLow: require('../assets/images/fuelLow.png'),
  fuelLowPipe: require('../assets/images/fuelLowPipe.png'),
  averageFuel: require('../assets/images/averageFuel.png'), 
  chevronDown: require('../assets/images/chevron-down.png'), 
  charger: require('../assets/images/charger.png'), 
  filter: require('../assets/images/filter.png'), 
  arrowDown: require('../assets/images/arrow-down.png'), 
  circleProgress: require('../assets/images/circleProgress.png'), 
  diesel: require('../assets/images/diesel.png'), 
  adblue: require('../assets/images/adblue.png'), 
  majorIssue: require('../assets/images/MajorIssue.png'), 
  speed: require('../assets/images/speed.png'), 
  swapDriving: require('../assets/images/swap_driving_apps_wheel.png'), 
  hourGlass: require('../assets/images/hourglass.png'), 
};
